output: ./dist/hyperledger-fabric

organizations:
  - name: Org1
    domain: org1.com
    orderers:
      - name: Orderer
        hostname: orderer
    bootstrap: true

  - name: Org2
    domain: org2.com
    peers: 2

  - name: Org3
    domain: org3.com
    peers: 2

profiles:
  - name: MultiChannel
    organizations:
      - Org1
      - Org2
      - Org3

