output = "./dist/hyperledger-fabric"

[[organizations]]
name = "Org1"
domain = "org1.com"
bootstrap = true

[[organizations.orderers]]
name = "Orderer"
hostname = "orderer"

[[organizations]]
name = "Org2"
domain = "org2.com"
peers = 2

[[organizations]]
name = "Org3"
domain = "org3.com"
peers = 2

[[profiles]]
name = "MultiChannel"
organizations = ["Org1", "Org2", "Org3"]
