output: ./dist/hyperledger-fabric

capabilities:
  channel: V2_0
  orderer: V2_0
  application: V2_5

organizations:
  - name: Org1
    domain: org1.com
    version:
      ca: 1.5.7
      fabric: 2.5
      peer: 2.5
      orderer: 2.5
    orderers:
      - name: Orderer
        subdomain: orderer
    bootstrap: true
    peers:
      - name: Peer0
        subdomain: peer0
        isAnchor: true

  - name: Org2
    domain: org2.com
    peers:
      - name: Peer0
        subdomain: peer0
        isAnchor: true

  - name: Org3
    domain: org3.com
    peers:
      - name: Peer0
        subdomain: peer0
        isAnchor: true


profiles:
  - &DefaultProfile
    name: DefaultProfile
    organizations:
      - Org1
      - Org2
      - Org3

channels:
  - name: multichannel
    profile: *DefaultProfile
